// CDN-ready media URL abstraction.
// - VITE_MEDIA_URL: media-serving origin (empty = same origin).
//   When a CDN is active, just set VITE_MEDIA_URL=https://cdn.example.com without
//   changing application code.
// - Uploaded files (/uploads/...): webp variants are generated by the backend on upload
//   with the <name>-w<width>.webp convention; the helper picks the nearest size.
// - External URLs (Unsplash etc.): resize/format params are appended when
//   the provider supports them.
const MEDIA_BASE = (import.meta.env.VITE_MEDIA_URL || '').replace(/\/$/, '');

const VARIANTSTST_WIDTHS = { thumbnail: 400, small: 800, medium: 1280, large: 1920 };

export function mediaUrl(url, size = 'small') {
  if (!url) return '';
  const width = VARIANTSTST_WIDTHS[size] ?? VARIANTSTST_WIDTHS.small;

  if (url.startsWith('/uploads/')) {
    const match = url.match(/^(\/uploads\/.+)\.(jpe?g|png|webp|avif|gif)$/i);
    if (match) return `${MEDIA_BASE}${match[1]}-w${width}.webp`;
    return `${MEDIA_BASE}${url}`;
  }

  if (/^https?:\/\/images\.unsplash\.com\//.test(url)) {
    const separator = url.includes('?') ? '&' : '?';
    return `${url}${separator}auto=format&fit=crop&w=${width}&q=75`;
  }

  return url;
}

// Original file URL (e.g. for full preview or download).
export function originalMediaUrl(url) {
  if (!url) return '';
  return url.startsWith('/uploads/') ? `${MEDIA_BASE}${url}` : url;
}
